spring.application.name=OBRS-BackEnd
server.port=8000

#database_Config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#hibernate_config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

#secrect-key_hidden
jwt.secret.key=${JWT_KEY}

#cloudinary_details
c_cName=${cloudinary_cloudname}
c_aK=${cloudinary_apikey}
c_aSk=${cloudinary_apisk}

logging.level.org.springframework.security=DEBUG

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

